/**
 * GENERATED by `pnpm gen:types` — do not edit. Derived from the *Command interfaces in this folder and in src/modules.
 */
import type { OrderDeliveryCommand } from '../modules/delivery.js';
import type { GigShiftCommand, GigSignupCommand } from '../modules/gig.js';
import type { RepayLoanCommand, TakeLoanCommand } from '../modules/loans.js';
import type { StudyOnlineCommand } from '../modules/online-study.js';
import type { SubscribeCommand, UnsubscribeCommand } from '../modules/subscriptions.js';
import type {
  BuyCarCommand,
  BuyTransitPassCommand,
  RepairCarCommand,
  SellCarCommand,
} from '../modules/transport.js';
import type { BuyAssetCommand, DepositCommand, SellAssetCommand, WithdrawCommand } from './bank.js';
import type { EnrollCommand, StudyCommand } from './education.js';
import type { BuyFoodCommand, EatMealCommand } from './food.js';
import type {
  MoveHomeCommand,
  PayRentCommand,
  RelaxCommand,
  RequestExtensionCommand,
} from './home.js';
import type { BuyItemCommand, RedeemPawnCommand, RepairCommand, SellItemCommand } from './items.js';
import type { ApplyJobCommand, AskRaiseCommand, WorkCommand } from './jobs.js';
import type { BuyLotteryCommand, ReadNewsCommand } from './misc.js';
import type { EndTurnCommand, EnterCommand, ExitCommand, MoveCommand } from './turn.js';

export type Command =
  | ApplyJobCommand
  | AskRaiseCommand
  | BuyAssetCommand
  | BuyCarCommand
  | BuyFoodCommand
  | BuyItemCommand
  | BuyLotteryCommand
  | BuyTransitPassCommand
  | DepositCommand
  | EatMealCommand
  | EndTurnCommand
  | EnrollCommand
  | EnterCommand
  | ExitCommand
  | GigShiftCommand
  | GigSignupCommand
  | MoveCommand
  | MoveHomeCommand
  | OrderDeliveryCommand
  | PayRentCommand
  | ReadNewsCommand
  | RedeemPawnCommand
  | RelaxCommand
  | RepairCommand
  | RepairCarCommand
  | RepayLoanCommand
  | RequestExtensionCommand
  | SellAssetCommand
  | SellCarCommand
  | SellItemCommand
  | StudyCommand
  | StudyOnlineCommand
  | SubscribeCommand
  | TakeLoanCommand
  | UnsubscribeCommand
  | WithdrawCommand
  | WorkCommand;

export type CommandType = Command['type'];

export const COMMAND_TYPES = [
  'ApplyJob',
  'AskRaise',
  'BuyAsset',
  'BuyCar',
  'BuyFood',
  'BuyItem',
  'BuyLottery',
  'BuyTransitPass',
  'Deposit',
  'EatMeal',
  'EndTurn',
  'Enroll',
  'Enter',
  'Exit',
  'GigShift',
  'GigSignup',
  'Move',
  'MoveHome',
  'OrderDelivery',
  'PayRent',
  'ReadNews',
  'RedeemPawn',
  'Relax',
  'Repair',
  'RepairCar',
  'RepayLoan',
  'RequestExtension',
  'SellAsset',
  'SellCar',
  'SellItem',
  'Study',
  'StudyOnline',
  'Subscribe',
  'TakeLoan',
  'Unsubscribe',
  'Withdraw',
  'Work',
] as const satisfies readonly CommandType[];
