/**
 * GENERATED by `pnpm gen:types` — do not edit. Derived from the *Command interfaces in this folder.
 */
import type { BuyAssetCommand, DepositCommand, SellAssetCommand, WithdrawCommand } from './bank.js';
import type { EnrollCommand, StudyCommand } from './education.js';
import type { BuyFoodCommand, EatMealCommand } from './food.js';
import type {
  MoveHomeCommand,
  PayRentCommand,
  RelaxCommand,
  RequestExtensionCommand,
} from './home.js';
import type { BuyItemCommand, RedeemPawnCommand, RepairCommand, SellItemCommand } from './items.js';
import type { ApplyJobCommand, AskRaiseCommand, WorkCommand } from './jobs.js';
import type { BuyLotteryCommand, ReadNewsCommand } from './misc.js';
import type { EndTurnCommand, EnterCommand, ExitCommand, MoveCommand } from './turn.js';

export type Command =
  | ApplyJobCommand
  | AskRaiseCommand
  | BuyAssetCommand
  | BuyFoodCommand
  | BuyItemCommand
  | BuyLotteryCommand
  | DepositCommand
  | EatMealCommand
  | EndTurnCommand
  | EnrollCommand
  | EnterCommand
  | ExitCommand
  | MoveCommand
  | MoveHomeCommand
  | PayRentCommand
  | ReadNewsCommand
  | RedeemPawnCommand
  | RelaxCommand
  | RepairCommand
  | RequestExtensionCommand
  | SellAssetCommand
  | SellItemCommand
  | StudyCommand
  | WithdrawCommand
  | WorkCommand;

export type CommandType = Command['type'];

export const COMMAND_TYPES = [
  'ApplyJob',
  'AskRaise',
  'BuyAsset',
  'BuyFood',
  'BuyItem',
  'BuyLottery',
  'Deposit',
  'EatMeal',
  'EndTurn',
  'Enroll',
  'Enter',
  'Exit',
  'Move',
  'MoveHome',
  'PayRent',
  'ReadNews',
  'RedeemPawn',
  'Relax',
  'Repair',
  'RequestExtension',
  'SellAsset',
  'SellItem',
  'Study',
  'Withdraw',
  'Work',
] as const satisfies readonly CommandType[];
