/** Soft-lit Modern vectors. Keep the four P0 outputs byte-for-byte stable. */
import { circle, ellipse, g, path, poly, rect } from '../art-default/svg.js';

export const MARKER = '<!-- art:modern generated by tools/art-modern -->';
const c = {
  cream: '#fff4df',
  sand: '#ebd5b5',
  coral: '#dc886b',
  coralLine: '#a75f50',
  teal: '#4c918b',
  tealLine: '#376e6b',
  glass: '#aed5d3',
  leaf: '#799d68',
  leafLight: '#a9bf83',
  wood: '#bf916a',
  gold: '#efba65',
  shadow: '#625e66',
};
const edge = (stroke: string) => ({ stroke, 'stroke-width': 1.5, 'stroke-linejoin': 'round' });
const line = (d: string, stroke: string, width = 1.5) =>
  path(d, 'none', { stroke, 'stroke-width': width, 'stroke-linecap': 'round' });
const gradient = (id: string, top: string, bottom: string) =>
  `<linearGradient id="${id}" x1="0" y1="0" x2="0.7" y2="1"><stop stop-color="${top}"/><stop offset="1" stop-color="${bottom}"/></linearGradient>`;
const defs = `<defs>${gradient('cream', '#fff6e5', '#e8cfad')}${gradient('coral', '#efa589', c.coral)}${gradient('teal', '#78b7ac', c.teal)}${gradient('glass', '#d7ebe4', '#8ebfbe')}${gradient('gold', '#f9d891', '#e7ad54')}<radialGradient id="shadow"><stop stop-color="${c.shadow}" stop-opacity="0.24"/><stop offset="1" stop-color="${c.shadow}" stop-opacity="0"/></radialGradient></defs>`;
const doc = (w: number, h: number, body: string) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}">${MARKER}${defs}${body}</svg>\n`;
const shadow = () => ellipse(127, 224, 108, 15, 'url(#shadow)');
const glass = (x: number, y: number, w: number, h: number) =>
  rect(x, y, w, h, 'url(#glass)', { rx: 4, ...edge(c.tealLine) }) +
  line(`M${x + 5} ${y + h - 9} L${x + w - 5} ${y + 7}`, c.cream, 3);
const plant = (x: number, y: number, scale = 1) =>
  g(
    path('M-8 0 L-6 14 H6 L8 0Z', c.coral, edge(c.coralLine)) +
      ellipse(-5, -6, 6, 10, c.leaf, { transform: 'rotate(-30 -5 -6)' }) +
      ellipse(5, -8, 6, 12, c.leafLight, { transform: 'rotate(25 5 -8)' }),
    { transform: `translate(${x} ${y}) scale(${scale})` },
  );
const homeSign = () => path('M-12 0 L0 -10 L12 0 V12 H3 V4 H-3 V12 H-12Z', c.cream);
const burger = () =>
  path('M-24 -4 Q-22 -26 0 -26 Q22 -26 24 -4Z', 'url(#gold)', edge('#bb8549')) +
  rect(-25, -1, 50, 6, c.leaf, { rx: 3 }) +
  rect(-24, 6, 48, 7, '#976449', { rx: 3 }) +
  path('M-22 14 H22 Q22 25 12 25 H-12 Q-22 25 -22 14Z', 'url(#gold)', edge('#bb8549')) +
  line('M-11 -14 l3 -3 M0 -18 l3 2 M11 -12 l3 -3', c.cream, 2);
const bankSign = () =>
  circle(0, 0, 18, c.cream) +
  path('M-9 -5 Q0 -16 9 -5 L0 11Z', c.teal) +
  line('M-6 -3 L0 3 L6 -3', c.cream, 2);

function pod(): string {
  let s = shadow();
  // Stepped silhouette; right face consistently recedes up and right.
  s += poly(
    [
      [48, 66],
      [72, 52],
      [196, 52],
      [173, 66],
    ],
    c.cream,
    edge('#b39b7f'),
  );
  s += poly(
    [
      [173, 66],
      [196, 52],
      [196, 204],
      [173, 220],
    ],
    '#c7a384',
    edge('#a78b73'),
  );
  s += rect(48, 66, 125, 154, 'url(#cream)', { rx: 5, ...edge('#b39b7f') });
  s += rect(43, 69, 135, 7, c.cream, { rx: 3 });
  // Raised coral pod and a planted shared roof deck.
  s += poly(
    [
      [42, 38],
      [63, 25],
      [144, 25],
      [125, 38],
    ],
    '#f4bc9d',
    edge(c.coralLine),
  );
  s += poly(
    [
      [125, 38],
      [144, 25],
      [144, 93],
      [125, 106],
    ],
    '#bf7660',
    edge(c.coralLine),
  );
  s += rect(42, 38, 83, 68, 'url(#coral)', { rx: 5, ...edge(c.coralLine) });
  s += glass(55, 51, 25, 35) + glass(89, 51, 25, 35);
  s += rect(53, 89, 63, 7, c.cream, { rx: 2 });
  s += plant(161, 53, 0.9) + plant(181, 48, 0.7);
  s += line('M146 65 V50 M190 59 V43 M146 52 L190 43', c.tealLine, 2);
  s += glass(61, 113, 36, 38) + glass(119, 113, 36, 38);
  s += rect(56, 145, 104, 11, c.teal, { rx: 3, ...edge(c.tealLine) });
  s += line('M61 145 V134 M85 145 V134 M132 145 V134 M155 145 V134 M61 134 H155', c.tealLine, 2);
  s += rect(58, 160, 105, 7, '#ba977b', { opacity: 0.25 });
  s += rect(96, 173, 35, 47, c.teal, { rx: 9, ...edge(c.tealLine) });
  s += rect(102, 179, 23, 28, 'url(#glass)', { rx: 6 });
  s += circle(124, 209, 2, c.gold);
  s += rect(92, 218, 44, 5, c.sand, { rx: 2 });
  s += circle(70, 183, 14, c.coral) + g(homeSign(), { transform: 'translate(70 181) scale(0.72)' });
  s += plant(153, 207, 1.05);
  s += line('M179 93 L188 88 M179 125 L188 120 M179 157 L188 152', '#e0c3a3', 4);
  return doc(240, 240, s);
}

function diner(): string {
  let s = shadow();
  s += poly(
    [
      [29, 121],
      [52, 105],
      [212, 105],
      [188, 121],
    ],
    c.cream,
    edge('#bba087'),
  );
  s += poly(
    [
      [188, 121],
      [212, 105],
      [212, 204],
      [188, 220],
    ],
    '#c67b61',
    edge(c.coralLine),
  );
  s += rect(29, 121, 159, 99, 'url(#cream)', { rx: 9, ...edge('#bba087') });
  s += rect(34, 199, 151, 21, 'url(#coral)', { rx: 3 });
  s += rect(22, 111, 175, 15, 'url(#coral)', { rx: 7, ...edge(c.coralLine) });
  s += line('M30 114 H186', '#f6c2a8', 3);
  // Oversized icon survives the 44px phone silhouette test.
  s += rect(96, 91, 12, 22, c.teal, { rx: 3 });
  s += g(burger(), { transform: 'translate(103 74) scale(1.35)' });
  s += glass(39, 153, 44, 38) + glass(91, 153, 38, 38);
  s += rect(139, 151, 35, 69, c.teal, { rx: 5, ...edge(c.tealLine) });
  s += rect(144, 156, 25, 42, 'url(#glass)', { rx: 3 });
  s += circle(166, 207, 2, c.gold);
  s += rect(27, 143, 160, 7, '#bd775c', { opacity: 0.22 });
  for (let i = 0; i < 8; i++) {
    const x = 26 + i * 20;
    s += path(`M${x + 4} 128 H${x + 24} L${x + 20} 143 H${x}Z`, i % 2 ? c.cream : c.coral);
    s += path(`M${x} 143 H${x + 20} V147 Q${x + 10} 154 ${x} 147Z`, i % 2 ? c.sand : '#c57760');
  }
  s += line('M31 129 H185', '#f5c9aa', 2);
  s += rect(192, 146, 11, 33, 'url(#glass)', { rx: 3 });
  s += plant(200, 202, 1.05);
  return doc(240, 240, s);
}

function bank(): string {
  let s = shadow();
  s += poly(
    [
      [44, 69],
      [67, 53],
      [196, 53],
      [174, 69],
    ],
    '#b1d1bb',
    edge(c.tealLine),
  );
  s += path('M174 69 L196 53 V203 L174 220Z', '#43807c', edge(c.tealLine));
  s += rect(44, 69, 130, 151, 'url(#teal)', { rx: 16, ...edge(c.tealLine) });
  s += path('M44 113 V85 Q44 69 60 69 H158 Q174 69 174 85 V113Z', 'url(#cream)', edge('#bba087'));
  s += line('M59 75 H155', c.cream, 3);
  s += g(bankSign(), { transform: 'translate(110 92)' });
  // Tall fins and broad entry give the bank a different rhythm from the pod.
  for (const x of [56, 85, 137]) s += glass(x, 125, 24, 36);
  s += rect(52, 168, 114, 6, '#356d68', { opacity: 0.4, rx: 2 });
  s += rect(80, 178, 59, 42, 'url(#glass)', { rx: 6, ...edge(c.tealLine) });
  s += line('M110 179 V217', c.tealLine, 2) + line('M105 199 V208 M115 199 V208', c.cream, 2);
  s += poly(
    [
      [72, 174],
      [85, 166],
      [151, 166],
      [144, 174],
    ],
    c.cream,
    edge('#bba087'),
  );
  s += rect(72, 174, 72, 6, c.sand, { rx: 2 });
  s += rect(77, 218, 67, 5, c.sand, { rx: 2 });
  s += rect(181, 107, 9, 51, '#80b2a7', { rx: 3 });
  s +=
    rect(51, 184, 19, 25, c.cream, { rx: 4 }) +
    rect(55, 188, 11, 9, c.teal, { rx: 2 }) +
    line('M56 202 H64', c.coralLine, 2);
  s += plant(159, 207, 1.1);
  return doc(240, 240, s);
}

const retailDoc = (body: string, id: string, light: string, dark: string) =>
  doc(240, 240, `<defs>${gradient(id, light, dark)}</defs>${body}`);
const shopWindow = (x: number, y: number, w: number, h: number) =>
  rect(x, y, w, h, 'url(#glass)', { rx: 3, ...edge(c.tealLine) });

function discountStore(): string {
  let s = shadow();
  s += poly(
    [
      [24, 111],
      [48, 96],
      [215, 96],
      [193, 111],
    ],
    '#f6d1a8',
    edge('#a7755c'),
  );
  s += poly(
    [
      [193, 111],
      [215, 96],
      [215, 204],
      [193, 220],
    ],
    '#af6b59',
    edge('#945b4f'),
  );
  s += rect(24, 111, 169, 109, 'url(#market)', { rx: 5, ...edge('#a7755c') });
  s += rect(18, 108, 183, 20, c.coral, { rx: 7, ...edge(c.coralLine) });
  s += line('M26 113 H192', '#f6c8a8', 3);
  // Broad basket shape doubles as the roof sign at phone scale.
  s += rect(96, 76, 48, 33, c.cream, { rx: 7, ...edge('#b39b7f') });
  s += path('M107 86 H133 L129 100 H111Z', c.coral, edge(c.coralLine));
  s += line('M111 85 Q120 73 129 85 M116 89 V97 M124 89 V97', c.coralLine, 2);
  s += shopWindow(33, 149, 49, 52) + shopWindow(89, 149, 43, 52);
  s += rect(143, 145, 39, 75, c.teal, { rx: 4, ...edge(c.tealLine) });
  s += shopWindow(148, 151, 29, 43) + circle(174, 205, 2, c.gold);
  for (let i = 0; i < 9; i++) {
    const x = 21 + i * 20;
    s += path(
      `M${x} 129 H${x + 20} L${x + 17} 147 H${x + 3}Z`,
      i % 2 ? c.cream : c.coral,
      edge(i % 2 ? '#bba087' : c.coralLine),
    );
  }
  s += rect(27, 215, 165, 6, '#cfaa8c', { rx: 2 });
  return retailDoc(s, 'market', '#f6dbc0', '#dfad90');
}

function boutique(): string {
  let s = shadow();
  s += poly(
    [
      [58, 83],
      [81, 67],
      [180, 67],
      [160, 83],
    ],
    '#e2c9d6',
    edge('#886e86'),
  );
  s += poly(
    [
      [160, 83],
      [180, 67],
      [180, 204],
      [160, 220],
    ],
    '#806883',
    edge('#735e76'),
  );
  s += rect(58, 83, 102, 137, 'url(#boutique)', { rx: 8, ...edge('#886e86') });
  s += rect(55, 83, 109, 31, c.cream, { rx: 7, ...edge('#b39b7f') });
  s += line('M65 88 H153', c.cream, 3);
  // A dress shape and single broad display window distinguish the narrow shop.
  s += circle(110, 92, 4, c.coral);
  s += path(
    'M104 98 L99 106 L103 108 L106 104 L104 111 H116 L114 104 L117 108 L121 106 L116 98Z',
    c.coral,
    edge(c.coralLine),
  );
  s += shopWindow(68, 135, 51, 66);
  s += line('M74 142 H113 M78 151 H109', c.cream, 2);
  s += g(
    path('M-7 0 L-14 8 L-9 12 L-5 8 V29 H5 V8 L9 12 L14 8 L7 0Z', c.coral, edge(c.coralLine)),
    { transform: 'translate(94 157) scale(0.8)' },
  );
  s += rect(125, 134, 25, 86, c.teal, { rx: 4, ...edge(c.tealLine) });
  s += shopWindow(129, 139, 17, 50);
  s += circle(145, 201, 2, c.gold);
  s += path('M51 116 H167 L160 134 H58Z', '#dfafbd', edge('#886e86'));
  for (let i = 0; i < 5; i++) {
    const x = 58 + i * 20;
    s += path(`M${x} 120 H${x + 20} L${x + 17} 134 H${x + 3}Z`, i % 2 ? c.cream : '#d499ad');
  }
  s += rect(57, 216, 104, 5, '#b89dab', { rx: 2 });
  return retailDoc(s, 'boutique', '#dbc4d5', '#b597b8');
}

function electronicsStore(): string {
  let s = shadow();
  s += poly(
    [
      [42, 101],
      [64, 86],
      [192, 86],
      [172, 101],
    ],
    '#aac5d0',
    edge('#55798b'),
  );
  s += poly(
    [
      [172, 101],
      [192, 86],
      [192, 205],
      [172, 220],
    ],
    '#527b89',
    edge('#456c7a'),
  );
  s += rect(42, 101, 130, 119, 'url(#deviceShop)', { rx: 5, ...edge('#55798b') });
  s += rect(37, 98, 141, 28, '#527f8c', { rx: 5, ...edge('#456c7a') });
  s += line('M45 102 H168', '#94bdc6', 3);
  s += rect(91, 67, 49, 32, c.cream, { rx: 6, ...edge('#b39b7f') });
  s += rect(101, 73, 29, 19, c.teal, { rx: 3, ...edge(c.tealLine) });
  s += line('M112 95 H119 M115 91 V95', c.tealLine, 2);
  // One large glass panel creates a lighter, lower rhythm than the bank.
  s += shopWindow(51, 140, 65, 66);
  s += line('M58 199 H109 M62 146 L103 146', c.cream, 3);
  s += rect(124, 138, 37, 82, '#426c79', { rx: 4, ...edge('#395e6a') });
  s += shopWindow(130, 145, 25, 49);
  s += circle(156, 204, 2, c.gold);
  s += rect(35, 127, 144, 8, c.cream, { rx: 3 });
  s += rect(44, 216, 132, 5, '#799aa3', { rx: 2 });
  return retailDoc(s, 'deviceShop', '#c4d9db', '#8fb2b9');
}

function grocery(): string {
  let s = shadow();
  s += poly(
    [
      [30, 114],
      [53, 99],
      [204, 99],
      [183, 114],
    ],
    '#b9d2a4',
    edge('#64875d'),
  );
  s += poly(
    [
      [183, 114],
      [204, 99],
      [204, 205],
      [183, 220],
    ],
    '#618c69',
    edge('#557c59'),
  );
  s += rect(30, 114, 153, 106, 'url(#produce)', { rx: 6, ...edge('#64875d') });
  s += rect(26, 107, 162, 25, c.cream, { rx: 6, ...edge('#b39b7f') });
  // Clustered fruit forms a recognisable produce cue without lettering.
  s += circle(92, 118, 9, c.coral) + circle(105, 118, 9, c.gold) + circle(118, 118, 9, c.coral);
  s += path('M101 108 Q105 101 112 107', 'none', {
    stroke: c.leaf,
    'stroke-width': 3,
    'stroke-linecap': 'round',
  });
  s += shopWindow(40, 157, 52, 45) + shopWindow(100, 157, 35, 45);
  s += rect(145, 151, 29, 69, c.teal, { rx: 4, ...edge(c.tealLine) });
  s += shopWindow(150, 157, 19, 40) + circle(169, 207, 2, c.gold);
  s += path('M24 133 H190 L181 152 H32Z', '#a0bd82', edge('#64875d'));
  for (let i = 0; i < 8; i++) {
    const x = 30 + i * 19;
    s += path(`M${x} 135 H${x + 19} L${x + 16} 151 H${x + 3}Z`, i % 2 ? c.cream : c.leaf);
  }
  s += rect(28, 216, 157, 6, '#8da779', { rx: 2 });
  return retailDoc(s, 'produce', '#d4e5bd', '#9dbb86');
}

function room(): string {
  // Fixed room camera. Right 40% contains only wall/floor so UI stays legible.
  let s = rect(0, 0, 1600, 1000, 'url(#cream)');
  s += poly(
    [
      [0, 0],
      [170, 105],
      [170, 650],
      [0, 790],
    ],
    '#ead1b3',
  );
  s += poly(
    [
      [0, 790],
      [170, 650],
      [1600, 650],
      [1600, 1000],
      [0, 1000],
    ],
    '#ccaa87',
  );
  s += path('M0 776 L170 639 H1600 V657 H170 L0 796Z', '#b99577');
  s += path('M170 657 H1600 V669 H170 L0 807 V796Z', '#896c5c', { opacity: 0.12 });
  s += poly(
    [
      [200, 650],
      [465, 650],
      [700, 1000],
      [275, 1000],
    ],
    '#f2d4a4',
    { opacity: 0.48 },
  );
  s += g(glass(0, 0, 98, 82) + line('M49 0 V82 M0 41 H98', c.cream, 3), {
    transform: 'translate(230 175) scale(3.6)',
  });
  s += rect(218, 157, 18, 325, c.coral, { rx: 8 }) + rect(581, 157, 22, 325, c.coral, { rx: 8 });
  s += rect(212, 148, 398, 15, c.wood, { rx: 7 });
  s += rect(227, 478, 370, 15, c.sand, { rx: 5 });
  // Shelves and shared kitchen live in the left 60%; no detail behind actions.
  s += rect(667, 223, 226, 18, c.wood, { rx: 5 });
  s += g(homeSign(), { transform: 'translate(710 187) scale(2)' });
  s += rect(677, 151, 66, 66, c.coral, { rx: 10 });
  s += g(homeSign(), { transform: 'translate(710 180) scale(1.9)' });
  s += plant(836, 199, 2.1);
  s += rect(663, 518, 241, 148, 'url(#teal)', { rx: 12, ...edge(c.tealLine) });
  s += rect(649, 506, 270, 20, c.cream, { rx: 7 });
  s += line('M780 534 V655 M684 546 H738 M806 546 H872', '#b2d1bd', 4);
  s += rect(823, 444, 52, 61, c.coral, { rx: 9 }) + rect(832, 451, 34, 24, c.cream, { rx: 5 });
  s += line('M844 486 H859', c.coralLine, 4);
  s += ellipse(488, 847, 400, 115, '#b4957d', { opacity: 0.15 });
  s += rect(90, 705, 714, 194, '#e7c6a5', { rx: 85 });
  s += rect(110, 734, 675, 127, '#f1d9b9', { rx: 61 });
  // Sofa sits left of host rather than becoming a counter across their face.
  s += rect(62, 584, 132, 166, c.tealLine, { rx: 20 });
  s += rect(46, 594, 151, 118, 'url(#teal)', { rx: 28 });
  s += rect(33, 675, 177, 68, 'url(#teal)', { rx: 23 });
  s += rect(29, 650, 32, 109, '#6ba499', { rx: 15 });
  s += rect(173, 650, 32, 109, '#4c8981', { rx: 15 });
  s += rect(76, 610, 80, 57, c.gold, { rx: 16 });
  s += g(plant(0, 0, 1), { transform: 'translate(759 794) scale(6)' });
  return doc(1600, 1000, s);
}

export function drawBenchmark(): Record<string, string> {
  return {
    'building.bank.svg': bank(),
    'building.burger-joint.svg': diner(),
    'building.clothing-boutique.svg': boutique(),
    'building.discount-store.svg': discountStore(),
    'building.electronics-store.svg': electronicsStore(),
    'building.grocery.svg': grocery(),
    'building.low-housing.svg': pod(),
    'interior.low-housing.svg': room(),
  };
}
