/**
 * Tiny SVG string helpers for the default art set (ART_SPEC 17.3, M9.13). Output is plain SVG that
 * passes the art sanitizer: shapes, groups, gradients, no text, no external references.
 */

/** Marks files this generator owns; `pnpm art:draw` only rewrites files carrying it. */
export const GENERATED_MARKER = '<!-- art:default generated by tools/art-default -->';

export const INK = '#2b2118';

type Attrs = Record<string, string | number | undefined>;

function attrs(a: Attrs): string {
  return Object.entries(a)
    .filter(([, v]) => v !== undefined)
    .map(([k, v]) => ` ${k}="${typeof v === 'number' ? round(v) : v}"`)
    .join('');
}

export function round(n: number): string {
  return String(Math.round(n * 10) / 10);
}

/** Outline attributes in the house style. */
export function ink(width = 4): Attrs {
  return {
    stroke: INK,
    'stroke-width': width,
    'stroke-linejoin': 'round',
    'stroke-linecap': 'round',
  };
}

export const rect = (
  x: number,
  y: number,
  w: number,
  h: number,
  fill: string,
  a: Attrs = {},
): string => `<rect${attrs({ x, y, width: w, height: h, fill, ...a })}/>`;
export const circle = (cx: number, cy: number, r: number, fill: string, a: Attrs = {}): string =>
  `<circle${attrs({ cx, cy, r, fill, ...a })}/>`;
export const ellipse = (
  cx: number,
  cy: number,
  rx: number,
  ry: number,
  fill: string,
  a: Attrs = {},
): string => `<ellipse${attrs({ cx, cy, rx, ry, fill, ...a })}/>`;
export const path = (d: string, fill: string, a: Attrs = {}): string =>
  `<path${attrs({ d, fill, ...a })}/>`;
export const poly = (
  pts: readonly (readonly [number, number])[],
  fill: string,
  a: Attrs = {},
): string =>
  `<polygon${attrs({ points: pts.map(([x, y]) => `${round(x)},${round(y)}`).join(' '), fill, ...a })}/>`;
export const line = (x1: number, y1: number, x2: number, y2: number, a: Attrs = {}): string =>
  `<line${attrs({ x1, y1, x2, y2, ...a })}/>`;
export const g = (body: string, a: Attrs = {}): string => `<g${attrs(a)}>${body}</g>`;

export function linear(id: string, stops: readonly [number, string][], vertical = true): string {
  const dir = vertical ? { x1: 0, y1: 0, x2: 0, y2: 1 } : { x1: 0, y1: 0, x2: 1, y2: 0 };
  return `<linearGradient${attrs({ id, ...dir })}>${stops
    .map(([o, c]) => `<stop${attrs({ offset: o, 'stop-color': c })}/>`)
    .join('')}</linearGradient>`;
}

/** A complete file: viewBox, marker, optional defs, body. */
export function svg(width: number, height: number, body: string, defs = ''): string {
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">`,
    GENERATED_MARKER,
    defs === '' ? '' : `<defs>${defs}</defs>`,
    body,
    '</svg>',
    '',
  ]
    .filter((l) => l !== '')
    .join('\n');
}

/** `#RRGGBB` darker by `f` (0..1). */
export function dark(hex: string, f: number): string {
  return mix(hex, '#000000', f);
}

/** `#RRGGBB` lighter by `f` (0..1). */
export function light(hex: string, f: number): string {
  return mix(hex, '#ffffff', f);
}

export function mix(a: string, b: string, f: number): string {
  const pa = Number.parseInt(a.slice(1), 16);
  const pb = Number.parseInt(b.slice(1), 16);
  const ch = (s: number): string =>
    Math.round(((pa >> s) & 0xff) * (1 - f) + ((pb >> s) & 0xff) * f)
      .toString(16)
      .padStart(2, '0');
  return `#${ch(16)}${ch(8)}${ch(0)}`;
}

/** Deterministic pseudo-random numbers for scattering details (seeded, no Math.random). */
export function rng(seed: number): () => number {
  let s = seed >>> 0 || 1;
  return () => {
    s ^= s << 13;
    s ^= s >>> 17;
    s ^= s << 5;
    return ((s >>> 0) % 10_000) / 10_000;
  };
}
