#!/usr/bin/env tsx
/**
 * `pnpm gen:types [--check]` — regenerates `packages/engine/src/commands/commands.generated.ts`,
 * the TypeScript `Command` union, from every `export interface <Name>Command extends BaseCommand`
 * in `packages/engine/src/commands/*.ts` and `packages/engine/src/modules/*.ts` (EXTENSIBILITY
 * 12.2: a module owns the commands it contributes). `--check` exits 1 when stale.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { format, resolveConfig } from 'prettier';

const dir = resolve(import.meta.dirname, '..', 'packages/engine/src/commands');
const modulesDir = resolve(import.meta.dirname, '..', 'packages/engine/src/modules');
const outFile = resolve(dir, 'commands.generated.ts');
const check = process.argv.includes('--check');

/** Source files that may declare commands, as import specifiers relative to the commands folder. */
const sources: { path: string; spec: string }[] = [];
for (const [base, prefix] of [
  [dir, './'],
  [modulesDir, '../modules/'],
] as const)
  for (const f of readdirSync(base).sort()) {
    if (
      !f.endsWith('.ts') ||
      f.endsWith('.test.ts') ||
      f === 'commands.generated.ts' ||
      f === 'registry.ts' ||
      f === 'common.ts' ||
      f === 'index.ts'
    )
      continue;
    sources.push({ path: resolve(base, f), spec: `${prefix}${f.replace(/\.ts$/, '.js')}` });
  }

const entries: { file: string; name: string; type: string }[] = [];
for (const { path, spec } of sources) {
  const src = readFileSync(path, 'utf8');
  const re = /export interface (\w+Command) extends BaseCommand \{[^}]*?type: '(\w+)'/g;
  for (const m of src.matchAll(re)) entries.push({ file: spec, name: m[1]!, type: m[2]! });
}
entries.sort((a, b) => a.type.localeCompare(b.type));

const byFile = new Map<string, string[]>();
for (const e of entries) byFile.set(e.file, [...(byFile.get(e.file) ?? []), e.name]);

const lines = [
  '/**',
  ' * GENERATED by `pnpm gen:types` — do not edit. Derived from the *Command interfaces in this folder and in src/modules.',
  ' */',
  ...[...byFile.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([file, names]) => `import type { ${names.sort().join(', ')} } from '${file}';`),
  '',
  `export type Command =\n${entries.map((e) => `  | ${e.name}`).join('\n')};`,
  '',
  `export type CommandType = Command['type'];`,
  '',
  `export const COMMAND_TYPES = [\n${entries.map((e) => `  '${e.type}',`).join('\n')}\n] as const satisfies readonly CommandType[];`,
  '',
];
const prettierConfig = (await resolveConfig(outFile)) ?? {};
const content = await format(lines.join('\n'), { ...prettierConfig, parser: 'typescript' });

if (check) {
  const current = existsSync(outFile) ? readFileSync(outFile, 'utf8') : '';
  if (current !== content) {
    console.error(`gen:types — ${outFile} is stale. Run \`pnpm gen:types\`. FAIL`);
    process.exit(1);
  }
  console.log(`gen:types — up to date (${entries.length} commands). OK`);
} else {
  writeFileSync(outFile, content);
  console.log(`gen:types — wrote ${entries.length} commands to ${outFile}`);
}
